/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import entity.HangDoi;

/**
 *
 * @author Trí Thức
 */
public class frmHangDoi extends javax.swing.JFrame {

	/**
	 * Creates new form frmHangDoi
	 */
	public frmHangDoi(ArrayList<HangDoi> arrListHangDoi) {
		initComponents();
		setLocationRelativeTo(null);
		tblModelDanhSach = (DefaultTableModel) tblDanhSach.getModel();
		loadDanhSachHangDoi(arrListHangDoi);
		btnThoat.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				closeWindow();

			}
		});
		btnXoa.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				xoaHoaDonCho();

			}
		});

		txtTimKiem.addKeyListener(new KeyAdapter() {
			@Override
			public void keyReleased(KeyEvent e) {
				if (!txtTimKiem.getText().trim().isEmpty()) {
					ArrayList<HangDoi> timKiem = timKiem(txtTimKiem.getText().trim(), arrListHangDoi);
					tblModelDanhSach.getDataVector().removeAllElements();
					loadDanhSachHangDoi(timKiem);
				} else {
					tblModelDanhSach.getDataVector().removeAllElements();
					loadDanhSachHangDoi(arrListHangDoi);
				}
			}
		});

		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
				if (JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình không ?", "Confirm",
						JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
					System.exit(0);
				}
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		pnTitle = new javax.swing.JPanel();
		lblTitle = new javax.swing.JLabel();
		pnDanhSach = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblDanhSach = new javax.swing.JTable();
		lblTimKiem = new javax.swing.JLabel();
		txtTimKiem = new javax.swing.JTextField();
		pnChucNang = new javax.swing.JPanel();
		btnThoat = new javax.swing.JButton();
		btnXoa = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		pnTitle.setBackground(new java.awt.Color(255, 255, 204));
		pnTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTitle.setText("Hóa Đơn Chưa Thanh Toán");

		javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
		pnTitle.setLayout(pnTitleLayout);
		pnTitleLayout.setHorizontalGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		pnTitleLayout.setVerticalGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE));

		pnDanhSach.setBackground(new java.awt.Color(255, 255, 204));
		pnDanhSach.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Hóa Đơn Chưa Thanh Toán",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

		tblDanhSach.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã Hóa Đơn", "Ngày Lập", "Tên Khách Hàng", "Số Điện Thoại" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tblDanhSach);

		lblTimKiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		lblTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTimKiem.setText("Tìm Kiếm");

		txtTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		txtTimKiem.setToolTipText("nhập tên khách hàng hoặc số điện thoại");

		javax.swing.GroupLayout pnDanhSachLayout = new javax.swing.GroupLayout(pnDanhSach);
		pnDanhSach.setLayout(pnDanhSachLayout);
		pnDanhSachLayout
				.setHorizontalGroup(pnDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
						.addGroup(pnDanhSachLayout.createSequentialGroup().addContainerGap()
								.addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(txtTimKiem)));
		pnDanhSachLayout.setVerticalGroup(pnDanhSachLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnDanhSachLayout.createSequentialGroup()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pnChucNang.setBackground(new java.awt.Color(255, 255, 204));
		pnChucNang.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		btnThoat.setBackground(new java.awt.Color(52, 84, 87));
		btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		btnThoat.setForeground(new java.awt.Color(255, 255, 255));
		btnThoat.setText("Thoát");

		btnXoa.setBackground(new java.awt.Color(52, 84, 87));
		btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		btnXoa.setForeground(new java.awt.Color(255, 255, 255));
		btnXoa.setText("Xóa");

		javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
		pnChucNang.setLayout(pnChucNangLayout);
		pnChucNangLayout.setHorizontalGroup(pnChucNangLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnChucNangLayout.createSequentialGroup().addGap(100, 100, 100)
						.addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
						.addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(100, 100, 100)));
		pnChucNangLayout.setVerticalGroup(pnChucNangLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChucNangLayout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(pnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(pnDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(pnChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)
						.addComponent(pnDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)
						.addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void closeWindow() {
		this.dispose();
	}

	private ArrayList<HangDoi> timKiem(String key, ArrayList<HangDoi> dsHangDoi) {
		ArrayList<HangDoi> dsKetQua = new ArrayList<>();
		for (HangDoi hangDoi : dsHangDoi) {
			if (hangDoi.getKhachHang().getHoTen().trim().contains(key)
					|| hangDoi.getKhachHang().getSoDT().trim().contains(key)) {
				dsKetQua.add(hangDoi);
			}
		}
		return dsKetQua;
	}

	public void xoaHoaDonCho() {
		int selRow = tblDanhSach.getSelectedRow();
		if (selRow < 0)
			JOptionPane.showMessageDialog(this, "Chọn Hóa Đơn Xóa !");
		else {
			tblModelDanhSach.removeRow(selRow);
			String maHDXoa = tblDanhSach.getValueAt(selRow, 0).toString().trim();
			jpnBanHang.getDSHangDoi().removeIf(hd -> hd.getMaHD().equalsIgnoreCase(maHDXoa));
			JOptionPane.showMessageDialog(this, "Đã Xóa " + maHDXoa);
		}
	}

	public JTable getTable() {
		return tblDanhSach;
	}

	private void loadDanhSachHangDoi(ArrayList<HangDoi> ds) {
		for (HangDoi hangDoi : ds) {
			Object[] row = { hangDoi.getMaHD(), hangDoi.getNgayLap(), hangDoi.getKhachHang().getHoTen().trim(),
					hangDoi.getKhachHang().getSoDT().trim() };
			tblModelDanhSach.addRow(row);
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnThoat;
	private javax.swing.JButton btnXoa;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblTimKiem;
	private javax.swing.JLabel lblTitle;
	private javax.swing.JPanel pnChucNang;
	private javax.swing.JPanel pnDanhSach;
	private javax.swing.JPanel pnTitle;
	private javax.swing.JTable tblDanhSach;
	private javax.swing.JTextField txtTimKiem;
	// End of variables declaration//GEN-END:variables

	private DefaultTableModel tblModelDanhSach;
}
